heat_template_version: 2015-10-15

description: >
  Template to install kargo on the server

parameters:
  node_names:
    description: Names of the node instances
    type: json

  node_ips:
    description: Ip's of the node instances
    type: json

  http_proxy:
    description: HTTP Proxy for agents installation
    type: string
    default: "none"

  https_proxy:
    description: HTTPS Proxy for agents installation
    type: string
    default: "none"

  instance:
    type: string
    description: The instance where this Software Configuration should be applied
    constraints:
      - custom_constraint: nova.server

resources:

  install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: node_names
        - name: node_ips
      outputs:
        - name: status
      config: { get_file: kargo/deploy.sh }

  install_deployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: { get_resource: install }
      server: { get_param: instance }
      signal_transport: HEAT_SIGNAL
      input_values:
        node_names: { get_param: node_names }
        node_ips: { get_param: node_ips }
      actions:
        - CREATE
        - UPDATE

outputs:
  install_status:
    value: { get_attr: [install_deployment, status] }

  install_stderr:
    value: { get_attr: [install_deployment, deploy_stderr] }
