heat_template_version: 2015-10-15

description: >
  Template to deploy and SSH public Key to hosts

parameters:

  ssh_pub_key:
    type: string
    description: SSH public key

  servers:
    type: json
    description: The instances where this Software Configuration should be applied

resources:

  install:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      inputs:
        - name: ssh_pub_key
      outputs:
        - name: status
      config: { get_file: ssh/add_public_key.sh }

  install_deployment:
    type: OS::Heat::SoftwareDeploymentGroup
    properties:
      config: { get_resource: install }
      servers: { get_param: servers }
      signal_transport: HEAT_SIGNAL
      input_values:
        ssh_pub_key: { get_param: ssh_pub_key }
      actions:
        - CREATE
        - UPDATE

outputs:
  install_status:
    value: { get_attr: [install_deployment, status] }

  install_stderr:
    value: { get_attr: [install_deployment, deploy_stderr] }
